blog/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  get 'welcome/index'
  
  resources :articles do 
    resources :comments 
    
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  root 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    
    has_many :comments, dependent: :destroy
    include ImageUploader[:image]
    validates :title, presence: true, length: { minimum: 5 }
    validates :title, presence: true, length: { minimum: 10 }
    validates :description, presence: true
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles
    
    VALID_EMAIL_REGEX = /A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    before_save { self.email = email.downcase }
    
    validates :name,
        presence: true,
        length: { maximum: 12 }
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    validates :password,
        presence: true,
        length: { minimum: 6 }
        
    has_secure_password
end 

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end 
    end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index 
        @articles = Article.all
    end 
    
    def show 
        @article = Article.find(params[:id])
    end
    
    def new 
        @article = Article.new
    end 
    
    def create 
        @article = Article.new(article_params)
        @article.user = current_user 
        
        
        if @article.save
           
            redirect_to @article 
        else
            render 'new'
        end
    end 
    
    def edit 
        @article = Article.find(params[:id])
    end 
    
    def update 
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    def destroy 
        @article = Article.find(params[:id])
        @article.destroy
        
        redirect_to articles_path
    end 
end 

private
   def article_params
       params.require(:article).permit(:image, :description, :title, :text)
   end 

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create 
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end 
    private 
       def comment_params
           params.require(:comment).permit(:commenter, :body)
       end 
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

  


  

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/pictures_helper.rb
module PicturesHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_article.html.erb
<div>
    <% if article.image_data? %>
    <%= image_tag article.image_url %> 
    <% end %>
    <p><%= article.title %> | <%= link_to 'Show', show_article_path(article) %></p>
</div>

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <% if @article.image.present? %>
      <%= image_tag @article.image_url %>
    <% end %> 
      
    <%= f.label :image %>
    <%= f.hidden_field :image, value: @article.cached_image_data %>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div> 
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  
<% end %> 

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><% if article.user %>
            <%= article.user.name %> 
          <% end %> 
        </td>
   
      
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', 
                                article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', articles_path %> 

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Image:</strong>
  <% if @article.image.present? %>
  <%= image_tag @article.image_url %>
  <% end %> 
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>


<h2>Comments</h2>
<%= render @article.comments %> 


<h2>Add a comment:</h2>
<%= render "comments/form" %>



<%= link_to 'Article List', articles_path %> 
<%= link_to 'Show', article_path(@article)%>

blog/app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
</p>
<p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "container" style = "padding-top:20px;"></div>
    <%= yield %>
  </body>
</html>

blog/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

blog/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

blog/app/views/welcome/index.html.erb
<h1>Hello, Blog App User!</h1>
<%= link_to 'My Blog', controller: 'articles' %>

<p>
    <% if current_user %>
      Logged in as <%= current_user.name %>.
      <%= link_to "Log Out", logout_path %>
    <% else %> 
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Log In", login_path %>
    <% end %> 
</p>